# Generated by Django 4.0.10 on 2024-11-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_filter_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='filter_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
