# Generated by Django 5.1.3 on 2024-12-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
