# Generated by Django 5.1.3 on 2024-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_first_name_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('executive', 'Executive'), ('user', 'User')], default='user', max_length=100),
        ),
    ]
