# Generated by Django 4.0.10 on 2024-11-03 07:41

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 3, 7, 41, 22, 435790, tzinfo=timezone.utc)),
        ),
    ]
