# Generated by Django 4.0.10 on 2024-11-03 07:54

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(default=job.models.default_expiry_date),
        ),
    ]
