# Generated by Django 4.0.10 on 2024-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
