# Generated by Django 4.0.10 on 2024-11-03 11:25

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Closed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract')], max_length=50, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(default=job.models.default_expiry_date, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Post Count'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('filled', 'Filled')], max_length=50, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='monthlyjobpost',
            name='month',
            field=models.IntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='monthlyjobpost',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Post Count'),
        ),
        migrations.AlterField(
            model_name='monthlyjobpost',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
