# Generated by Django 5.1.3 on 2024-11-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_expiry_date'),
        ('job', '0008_alter_job_date_closed_alter_job_date_posted_and_more'),
    ]

    operations = [
    ]
