# Generated by Django 5.1.3 on 2024-11-18 12:38

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_merge_20241111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(default=job.models.default_expiry_date, verbose_name='Expiry Date'),
        ),
    ]
