# Generated by Django 5.1.3 on 2024-11-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_job_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='monthlyjobpost',
            name='post_count',
        ),
    ]
