# Generated by Django 5.1.3 on 2024-11-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_job_post_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Post Count'),
        ),
        migrations.AddField(
            model_name='monthlyjobpost',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Post Count'),
        ),
    ]
