# Generated by Django 5.1.3 on 2024-11-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_post_count_monthlyjobpost_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Post Count'),
        ),
    ]
